//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDKCMS.FrontEnd.Layout {
    
    
    public partial class Column_Right {
        
        /// <summary>
        /// TuyenSinh_Home1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.Project.TuyenSinh_Home TuyenSinh_Home1;
        
        /// <summary>
        /// Search_Khoahoc1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.Project.Search_Khoahoc Search_Khoahoc1;
        
        /// <summary>
        /// Subcategory_2level1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.Subcategory_2level Subcategory_2level1;
        
        /// <summary>
        /// CamNhan_Sub1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.Project.CamNhan_Sub CamNhan_Sub1;
        
        /// <summary>
        /// Music_Home1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.Music_Home Music_Home1;
        
        /// <summary>
        /// News_Sub1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.Project.News_Sub News_Sub1;
        
        /// <summary>
        /// Video_RightSub1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.Video_RightSub Video_RightSub1;
    }
}
