//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDKCMS.FrontEnd.Layout {
    
    
    public partial class Header {
        
        /// <summary>
        /// Facebook_Like1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.Facebook_Like Facebook_Like1;
        
        /// <summary>
        /// Nav_Main_Image1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.Nav_Main_Image Nav_Main_Image1;
    }
}
