//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDKCMS.FrontEnd.Layout {
    
    
    public partial class Home_AloneArea {
        
        /// <summary>
        /// News_Home1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.News_Home News_Home1;
        
        /// <summary>
        /// Gallery_Home1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.Gallery_Home Gallery_Home1;
        
        /// <summary>
        /// Video_Home1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.Video_Home Video_Home1;
        
        /// <summary>
        /// CamNhan_Home1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.Project.CamNhan_Home CamNhan_Home1;
    }
}
