//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDKCMS.FrontEnd.Layout {
    
    
    public partial class Layout_Zone_TuyenSinh_Item {
        
        /// <summary>
        /// SpecialInZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.SpecialInZone SpecialInZone1;
        
        /// <summary>
        /// lnkZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink lnkZone;
        
        /// <summary>
        /// SubCategory1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.SubCategory SubCategory1;
        
        /// <summary>
        /// TuyenSinh_Detail1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.Project.TuyenSinh_Detail TuyenSinh_Detail1;
    }
}
