//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDKCMS.FrontEnd.Layout {
    
    
    public partial class Layout_Zone_ClassRegister {
        
        /// <summary>
        /// Banner_InZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.UserControls.Banner_InZone Banner_InZone1;
        
        /// <summary>
        /// ClassRegister1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iDKCMS.FrontEnd.Project.ClassRegister ClassRegister1;
    }
}
